@host_name=http://localhost:8000/api/v1
//get full product 
GET {{host_name}}/product
###

// pagination
GET {{host_name}}/product?page=1
###

//register
POST {{host_name}}/register
content-type: application/json

{
    "name":"loky",
    "email":"abc@gmail.com",
    "password":123458,
    "avator":"1234567.jpg"
}
###

//login
POST {{host_name}}/login
content-type: application/json

{
    "email":"abc@gmail.com",
    "password":"123458"
}
