//get full product 
GET http://localhost:8000/api/v1/product
###

// pagination
GET http://localhost:8000/api/v1/product?page=1
###


@hostname =http://localhost:8000/api/v1
//register
POST {{hostname}}/register 
content-type: application/json

{
    "name":"loky",
    "email":"abc@gmail.com",
    "password":123456,
    "avator":"1234567.jpg"
}